#ifndef __CONFIG_STM32_STROBOSCOPIC_SRC_STM32_HRTIM_CONTROL_H
#define __CONFIG_STM32_STROBOSCOPIC_SRC_STM32_HRTIM_CONTROL_H

// STM32 HRTIM Control driver specific MACROS

// Can be also defined at strobo.h application layer

// IOCTL
#define STM32_HRTIM_MOD_DUTY 0
#define STM32_HRTIM_MOD_TIMD_CH2_SET 1
#define STM32_HRTIM_MOD_TIMD_CH2_RST 2


#endif
